spring:
  security:
    user:
      name: DEVUSER
      password: 123456
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_NAME:db-users}?serverTimezone=UTC
    username: ${DB_USERNAME:DEVUSER}
    password: ${DB_PASSWORD:DEVPASSWORD22}