spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_NAME:db-users}?serverTimezone=UTC
    username: ${DB_USERNAME:DEVUSER}
    password: ${DB_PASSWORD:DEVPASSWORD22}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 9090
  servlet:
    context-path: /security-service/v1/

jwt:
  header: Authorization
  # This token must be encoded using Base64 (type `echo 'my-secret-key=jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4kiwoKWldpwpVpmdkeeeLEetWXXoymrmtkrklsskddyTTkeekrerUjUYn'|base64` on your command line)
  base64-secret: bXktc2VjcmV0LWtleT1qeGdFUWVYSHVQcThWZGJ5WUZOa0FOZHVkUTUzWVVuNGtpd29LV2xkcHdwVnBtZGtlZWVMRWV0V1hYb3ltcm10a3JrbHNza2RkeVRUa2Vla3JlclVqVVluCg==
  # Token is valid for 24 hours
  token-validity-in-seconds: 86400
  # Token is valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000